# Generated by Django 2.1.5 on 2022-10-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20221025_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order_list',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Order'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Products'),
        ),
    ]
